import Image from "next/image";
import "./globals.css";
import Link from "next/link";
import NavBar from "@/components/nav";
import CenterDetailPage from "@/components/centerDetailPage";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko" className="h-screen font-NanumSquareRound text-defaultBlack">
      <body className="flex flex-col h-screen tracking-tighter ">
        <header className="fixed top-0 left-0 right-0 flex items-center gap-2 px-8 py-4 bg-white border-b md:gap-0 md:justify-between border-b-slate-200">
          <h1 className="text-[15px] md:text-[20px] tracking-normal font-NotoSansKR font-semibold">
            <Link href={"/"}>디디다: 충청남도 청소년활동자원맵</Link>
          </h1>
          <Image src={"/cn-brand-logo.svg"} className="hidden h-8 md:block w-36" width={214} height={48} alt="브랜드로고" />
        </header>

        <div className="flex flex-col h-full md:flex-row md:flex-1 pt-[65px]">
          <NavBar />
          <section className="w-full overflow-y-auto bg-white border-r md:shadow-lg md:max-w-sm border-r-slate-200">{children}</section>
          {/* 프로그램 상세 목록 컴포넌트 */}
          <CenterDetailPage />
          <div className="flex items-center justify-center flex-1 bg-fuchsia-50">
            <div>맵 위치</div>
          </div>
        </div>
      </body>
    </html>
  );
}
