import Image from "next/image";
import "./globals.css";
import Link from "next/link";
import NavBar from "@/components/nav";
import CenterDetailPage from "@/components/centerDetailPage";
import Header from "@/components/header";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko" className="h-screen font-NanumSquareRound text-defaultBlack">
      <body className="flex flex-col h-screen tracking-tighter ">
        <Header />
        <div className="flex flex-col h-full md:flex-row md:flex-1 pt-[65px]">
          <NavBar />
          <section className="w-full overflow-y-auto bg-white border-r md:shadow-lg md:max-w-sm border-r-slate-200">{children}</section>
          {/* 프로그램 상세 목록 컴포넌트 */}
          <CenterDetailPage />
          <div className="flex items-center justify-center flex-1 bg-fuchsia-50">
            <div>맵 위치</div>
          </div>
        </div>
      </body>
    </html>
  );
}
